### ISSUE TITLE
Increase the re throw time

### ISSUE THREAD

**Issue by NanShang126** [GenesisHacks/Simple-Autofish#2]
Increase the re throw time
If the interval is too short, the fishing will be stuck, and the last item will be hooked when fishing

**Comment by GenesisHacks** [comment]
This has never happened to me while using it and I've tested it for hours. But if it's something you're encountering I can update to hopefully fix this.

**Comment by GenesisHacks** [comment]
Uploaded a new version with a slightly longer time. Should hopefully be processed soon.
https://www.curseforge.com/minecraft/mc-mods/simple-autofish

**Comment by GenesisHacks** [comment]
Version 1.3.0
